/* eslint-disable */
// AUTO-GENERATED by `npm run locales:generate`.  Do not edit by hand.
// Source: .twosky.json → project_id: home_v2 → languages
// Excludes: (none)

export type LocaleMessage = Record<string, string>;

import en from 'panel/__locales/en.json';

export const LOCALE_LOADERS: Record<string, () => Promise<any>> = {
    'zh-cn': () => import(/* webpackChunkName: "locale.zh-cn" */ 'panel/__locales/zh-cn.json'),
    'zh-tw': () => import(/* webpackChunkName: "locale.zh-tw" */ 'panel/__locales/zh-tw.json')
};

export const LOCALE_CODES = new Set(['en', 'zh-cn', 'zh-tw']);

export const LOCALES: Record<string, LocaleMessage> = {
    en: en,
};

